#!/bin/bash

# Distributed Split Learning Training Script
# This script helps you understand how to run the training

echo "=========================================="
echo "Split Learning Distributed Training"
echo "=========================================="
echo ""
echo "To run distributed training, open TWO terminals:"
echo ""
echo "Terminal 1 (Server - Device 1):"
echo "  cd $(pwd)"
echo "  python ws_client.py --device_id 1 \\"
echo "    --init_checkpoint ../pretrained_checkpoints/gpt2-pytorch_model.bin \\"
echo "    --model_card gpt2.sm \\"
echo "    --client_layers 6 \\"
echo "    --server_device cuda:0"
echo ""
echo "Terminal 2 (Client - Device 0):"
echo "  cd $(pwd)"
echo "  python ws_client.py --device_id 0 \\"
echo "    --train_data ../data/e2e/train.jsonl \\"
echo "    --valid_data ../data/e2e/valid.jsonl \\"
echo "    --init_checkpoint ../pretrained_checkpoints/gpt2-pytorch_model.bin \\"
echo "    --model_card gpt2.sm \\"
echo "    --client_layers 6 \\"
echo "    --client_device cuda:0 \\"
echo "    --train_batch_size 1 \\"
echo "    --seq_len 128 \\"
echo "    --grad_acc 4 \\"
echo "    --epochs 1 \\"
echo "    --output_dir ./outputs"
echo ""
echo "=========================================="
echo "Notes:"
echo "- Start Terminal 1 (server) first"
echo "- Then start Terminal 2 (client)"
echo "- Ensure ports 8765 is available"
echo "- Monitor both terminals for progress"
echo "=========================================="
